targets:
  $default:
    builders:
      json_serializable|json_serializable:
        options:
          explicit_to_json: true
      freezed|freezed:
        options:
          super-parameters: true
          enhanced-enums: true
