name: fitapp_domain
description: Contains shared models for FitApp.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed: ^3.0.6
  freezed_annotation: any
  json_annotation: any
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.25.8
