name: app
description: "Flutter fitness application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: 10.0.1
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  fitapp_domain:
    path: ../domain
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  freezed: ^3.0.6
  freezed_annotation: any
  golden_toolkit: ^0.15.0
  hive: ^2.2.3
  json_annotation: any
  path_provider: ^2.1.5
  uuid: ^4.5.1

dev_dependencies:
  auto_route_generator: 10.0.1
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.5
#  flutter_test:
#    sdk: flutter
  lints: ^6.0.0
  test: ^1.25.15

flutter:
  uses-material-design: true

  assets:
   - assets/images/flags/eng.png
   - assets/images/flags/rus.png

flutter_intl:
  enabled: true
